name: Meat Me In St Louis
favicon: null
layout_spectrum: 0.5031063966453075
typography_spectrum: 0.18953415052965283
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4113466185517609
  lightness: 0.5862664678134024
  saturation: 0.8059288237709552
  rhythmicContrast: 0.8028720763977617
purpose: []
